#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <path_to_image>"
    exit 1
fi

IMAGE="$1"

notify-send "Changing theme" "Applying new wallpaper and updating colors, please wait until confirmation..."

swww img "$IMAGE" --transition-type=grow --transition-pos top-right

wal -i "$IMAGE" -n -s -t -e

# Make neovim to use pywal colors
# python3 $HOME/.config/nvim/pywal/chadwal.py

# Generate colors with matugen
matugen image $IMAGE

# Refresh waybar
pkill waybar
waybar > /dev/null 2>&1 &

# Refresh swaync
pkill swaync
swaync > /dev/null 2>&1 &

notify-send "Theme applied" "Wallpaper and theme updated successfully!"
